version: '2'
services:
    snsamaauto-app:
        image: snsamaauto
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://snsamaauto-mysql:3306/snsamaauto?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=snsamaauto-elasticsearch:9300
        ports:
            - 8080:8080
    snsamaauto-mysql:
        extends:
            file: mysql.yml
            service: snsamaauto-mysql
    snsamaauto-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: snsamaauto-elasticsearch
